# Generated by Django 4.1 on 2026-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_department_model_employee_model_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='employee_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('HR', 'HR'), ('MANAGER', 'MANAGER')], max_length=25),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('HR', 'HR'), ('MANAGER', 'MANAGER')], max_length=100),
        ),
    ]
