# Generated by Django 4.1 on 2026-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_alter_employee_model_employee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='employee_type',
        ),
    ]
